{% set name = "dcap" %}
{% set version = "2.47.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dCache/{{ name }}/archive/{{ version }}.tar.gz
  sha256: dda98990d93cded815ee425101674ad2f48438fff76b3d4d5d3f91e380e9cc49
  patches:
    - 0001-Don-t-build-the-telnet-plugin.patch  # [osx]
    - 0002-Check-for-_DARWIN_FEATURE_ONLY_64_BIT_INODE-and-defi.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - automake
    - make
    - pkg-config
    - libtool
    - sed
  host:
    - gct
    - krb5
    - openssl
    - zlib
    # Required for make check
    - cunit

test:
  commands:
    - which dccp

about:
  home: https://www.dcache.org
  license: LGPL-2.0-only
  license_family: GPL
  license_file: COPYING.LIB
  summary: The dCache dccp client
  description: |
    dcap is a POSIX like interface for accessing dCache, allowing unmodified
    applications to access dCache transparently. This access method uses a
    proprietary data transfer protocol, which can emulate POSIX access across
    the LAN or WAN.
  doc_url: https://www.dcache.org/manuals/libdcap.shtml
  dev_url: https://github.com/dCache/dcap

extra:
  recipe-maintainers:
    - chrisburr
