{% set name = "dcap" %}
{% set version = "2.47.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dCache/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 050a8d20c241abf358d5d72586f9abc43940e61d9ec9480040ac7da52ec804ac
  patches:
    - 0001-PATCH-Missing-declaration.patch
    - 0002-Don-t-build-the-telnet-plugin.patch  # [osx]
    - 0003-Recent-macOS-SDKs-don-t-define-stat64-as-it-s-identi.patch
    - 0004-Since-macOS-10.10-ntohll-htonll-are-provided-as-pre-.patch

build:
  number: 6
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - automake
    - make
    - pkg-config
    - libtool
    - sed
  host:
    - gct
    - krb5
    - openssl
    - zlib
    # Required for make check
    - cunit

test:
  commands:
    - which dccp

about:
  home: https://www.dcache.org
  license: LGPL-2.0-only
  license_family: GPL
  license_file: COPYING.LIB
  summary: 'The dCache dccp client'
  description: |
    dcap is a POSIX like interface for accessing dCache, allowing unmodified
    applications to access dCache transparently. This access method uses a
    proprietary data transfer protocol, which can emulate POSIX access across
    the LAN or WAN.
  doc_url: https://www.dcache.org/manuals/libdcap.shtml
  dev_url: https://github.com/dCache/dcap

extra:
  recipe-maintainers:
    - chrisburr
